// crates/sl-frontend/src/components/layout/Navbar.tsx
import { Maximize, Minus, X } from 'lucide-react';
import { Button } from '../ui/button';
import {
	handleWindowClose,
	handleWindowMinimize,
	handleWinndowMaximize,
} from '@/lib/commands/window';

export const Navbar = () => {
	return (
		<nav
			className="bg-[#1B1D21] w-full flex h-[3.3rem] justify-end items-center p-1"
			data-tauri-drag-region
		>
			<div className="flex gap-[0.1rem]">
				<Button
					variant="ghost"
					onClick={handleWindowMinimize}
					className="group hover:bg-[#89C733] rounded-full p-0 flex items-center justify-center w-11 h-11 transition-all duration-300"
				>
					<Minus className="text-white group-hover:text-black transition-all duration-300 transform group-hover:scale-105" />
				</Button>
				{/*hover:bg-slate-500/20 */}
				<Button
					variant="ghost"
					onClick={handleWinndowMaximize}
					className="group hover:bg-[#FCB335] rounded-full p-0 flex items-center justify-center w-11 h-11 transition-all duration-300"
				>
					<Maximize className="text-white group-hover:text-black transition-all duration-300 transform group-hover:scale-105" />
				</Button>
				<Button
					variant="ghost"
					onClick={handleWindowClose}
					className="group hover:bg-red-400 rounded-full p-0 flex items-center justify-center w-11 h-11 transition-all duration-300"
				>
					<X className="text-white group-hover:text-black transition-all duration-300 transform group-hover:scale-105" />
				</Button>
			</div>
		</nav>
	);
};

// crates/sl-frontend/src/components/Navbar.vue
<template>
  <nav
    class="w-full flex h-[3.4rem] justify-between items-center p-2 bg-[#1b1d21]"
    data-tauri-drag-region
  >
    <div class="flex items-center gap-2 ml-[0.4rem]">
      <img
        width="37"
        height="37"
        src="/images/synthlauncher-logo.png"
        alt="SynthLauncher Logo"
      />
      <h1 class="text-xl font-bold text-white">SynthLauncher</h1>
    </div>

    <div class="flex gap-[0.1rem]">
      <WindowControl
        @click="handleWindowMinimize"
        :icon="MinusIcon"
        label="Minimize Window"
        class="hover:bg-[#8fe21a]"
      />
      <WindowControl
        @click="handleWindowMaximize"
        :icon="MaximizeIcon"
        label="Maximize Window"
        class="hover:bg-[#fcbd35]"
      />
      <WindowControl
        @click="handleWindowClose"
        :icon="XIcon"
        label="Close Window"
        class="hover:bg-red-400"
      />
    </div>
  </nav>
</template>

<script setup lang="ts">
import { Minus as MinusIcon, Maximize as MaximizeIcon, X as XIcon } from 'lucide-vue-next'
import WindowControl from './WindowControl.vue'
import {
  handleWindowMinimize,
  handleWindowMaximize,
  handleWindowClose,
} from '../lib/commands/window'
</script>
