// crates/sl-frontend/src/components/layout/navbar.tsx
import { Maximize, Minus, X } from 'lucide-react';
import { Button } from '@/components/ui/button';
import {
	handleWindowClose,
	handleWindowMinimize,
	handleWindowMaximize,
} from '@/lib/commands/window';
import { cn } from '@/lib/utils';

const WindowControl = ({
	onClick,
	icon,
	label,
	className,
}: {
	onClick: () => void;
	icon: JSX.Element;
	label: string;
	className: string;
}) => (
	<Button
		variant="ghost"
		onClick={onClick}
		aria-label={label}
		className={cn(
			'group rounded-full p-0 flex items-center justify-center w-11 h-11 transition-all duration-300',
			className
		)}
	>
		<span className="text-white group-hover:text-black transition-all duration-300 transform group-hover:scale-105">
			{icon}
		</span>
	</Button>
);

export const Navbar = () => {
	return (
		<nav
			className="w-full flex h-[3.3rem] justify-between items-center p-1 bg-layout"
			data-tauri-drag-region
		>
      <div className='flex items-center gap-2 ml-[0.75rem]'>
        <img width={35} height={35} src="/images/synthlauncher-logo.png" alt="SynthLauncher Logo" />
        <h1 className='text-xl font-bold'>SynthLauncher</h1>
      </div>

			<div className="flex gap-[0.1rem]">
				<WindowControl
					onClick={handleWindowMinimize}
					icon={<Minus />}
					label="Minimize Window"
					className="hover:bg-[#8fe21a]"
				/>
				<WindowControl
					onClick={handleWindowMaximize}
					icon={<Maximize />}
					label="Maximize Window"
					className="hover:bg-[#fcbd35]"
				/>
				<WindowControl
					onClick={handleWindowClose}
					icon={<X />}
					label="Close Window"
					className="hover:bg-red-400"
				/>
			</div>
		</nav>
	);
};

// crates/sl-frontend/src/components/Navbar.vue
<template>
  <nav
    class="w-full flex h-[3.3rem] justify-between items-center p-1 bg-layout bg-neutral-800"
    data-tauri-drag-region
  >
    <div class="flex items-center gap-2 ml-[0.75rem]">
      <img
        width="35"
        height="35"
        src="/images/synthlauncher-logo.png"
        alt="SynthLauncher Logo"
      />
      <h1 class="text-xl font-bold text-white">SynthLauncher</h1>
    </div>

    <div class="flex gap-[0.1rem]">
      <WindowControl
        @click="handleWindowMinimize"
        :icon="MinusIcon"
        label="Minimize Window"
        class="hover:bg-[#8fe21a]"
      />
      <WindowControl
        @click="handleWindowMaximize"
        :icon="MaximizeIcon"
        label="Maximize Window"
        class="hover:bg-[#fcbd35]"
      />
      <WindowControl
        @click="handleWindowClose"
        :icon="XIcon"
        label="Close Window"
        class="hover:bg-red-400"
      />
    </div>
  </nav>
</template>

<script setup lang="ts">
import { Minus as MinusIcon, Maximize as MaximizeIcon, X as XIcon } from 'lucide-vue-next'
import WindowControl from './WindowControl.vue'
import {
  handleWindowMinimize,
  handleWindowMaximize,
  handleWindowClose,
} from '../lib/commands/window'
</script>
