// crates/sl-frontend/src/components/StoreCard.vue
<template>
    <div class="flex gap-4 p-4 bg-[#202227] rounded-lg">
        <img :src="icon" alt="Store Card Icon" class="w-24 h-24 rounded-md">

        <div class="flex flex-col gap-2">
            <h1 class="text-white text-2xl font-bold">
                {{ title }}

                <span class="text-neutral-400 text-sm font-normal">
                    by {{ author }}
                </span>
            </h1>

            <p class="text-gray-400 text-sm mt-1 line-clamp-2">{{ description }}</p>

            <div class="flex gap-1 text-gray-400 text-sm items-center">
                <DownloadIcon class="w-4 h-4" />
                <span>{{ downloads }} downloads</span>
            </div>
        </div>
    </div>
</template>

<script setup lang="ts">
import { DownloadIcon } from 'lucide-vue-next';

defineProps<{
    icon?: any,
    title: string,
    author: string,
    description: string,
    downloads: number,
}>();
</script>

// crates/sl-frontend/src/components/StoreCard.tsx
import { Download, Heart } from 'lucide-react';
import { Button } from './ui/button';
import { StoreCardProps } from '@/lib/types/store/store';

export const StoreCard = ({
	name,
	author,
	description,
	downloads,
	followers,
	imageUrl,
}: StoreCardProps) => {
	return (
		<div className="bg-[#1D2026] rounded-lg p-5 flex gap-3">
			<img src={imageUrl} alt="mod icon" className="w-24 h-24 rounded-md" />

			<div className="flex flex-col grow">
				<h1 className="text-white text-lg font-bold flex gap-2 items-center">
					{name}
					<span className="text-gray-500 font-normal">by {author}</span>
				</h1>
				<p className="text-gray-500 grow">{description}</p>
			</div>

			<div className="flex flex-col items-end">
				<div className="flex gap-1 items-center text-gray-500">
					<Download className="w-4 h-4" />
					<p>{downloads} Downloads</p>
				</div>

				<div className="flex gap-1 items-center text-gray-500">
					<Heart className="w-4 h-4" />
					<p>{followers} Followers</p>
				</div>

				<Button className="mt-auto" variant="install">
					<Download className="w-4 h-4" />
					Install
				</Button>
			</div>
		</div>
	);
};
