// crates/sl-frontend/src/components/InstanceCard.tsx
import React from 'react';
import { Play, MoreVertical, Clock, Calendar } from 'lucide-react';

type InstanceCardProps = {
  title: string;
  version: string;
  modLoader?: string;
  modCount?: number;
  lastPlayed: string;
  image: string;
  favorite?: boolean;
};

const InstanceCard: React.FC<InstanceCardProps> = ({
  title,
  version,
  modLoader,
  modCount,
  lastPlayed,
  image,
  favorite,
}) => {
  return (
    <div className="bg-gray-800 rounded-lg overflow-hidden group transition-all duration-200 hover:shadow-lg hover:shadow-emerald-900/10">
      <div className="relative h-35 overflow-hidden">
        <img 
          src={image} 
          alt={title} 
          className="w-full h-full object-cover transition-transform duration-500"
        />
        <div className="absolute inset-0 bg-gradient-to-t from-gray-900/80 to-transparent"></div>
        
        <div className="absolute bottom-3 left-3 right-3 flex items-end justify-between">
          <div>
            <h3 className="text-white font-bold text-lg leading-tight">{title}</h3>
            <div className="flex items-center gap-1.5 text-xs text-gray-300 mt-0.5">
              <span>{version}</span>
              {modLoader && (
                <>
                  <span className="w-1 h-1 bg-gray-500 rounded-full"></span>
                  <span>{modLoader}</span>
                </>
              )}
              {modCount !== undefined && (
                <>
                  <span className="w-1 h-1 bg-gray-500 rounded-full"></span>
                  <span>{modCount} mods</span>
                </>
              )}
            </div>
          </div>
          
          {favorite && (
            <div className="bg-amber-500/90 text-amber-950 text-xs rounded-full px-2 py-0.5 font-medium">
              Favorite
            </div>
          )}
        </div>
      </div>
      
      <div className="p-3 flex items-center justify-between">
        <div className="flex items-center gap-2 text-xs text-gray-400">
          <Clock size={14} />
          <span>{lastPlayed}</span>
        </div>
        
        <div className="flex items-center gap-2">
          <button className="text-gray-400 hover:text-white transition-colors p-1">
            <MoreVertical size={18} />
          </button>
          <button className="bg-purple-600 hover:bg-purple-500 text-white rounded-full w-8 h-8 flex items-center justify-center transition-colors">
            <Play size={16} className="ml-0.5" />
          </button>
        </div>
      </div>
    </div>
  );
};

export default InstanceCard;

// crates/sl-frontend/src/components/instances/InstanceCard.vue
<script lang="ts" setup>
import { PlayIcon } from 'lucide-vue-next';
import { instancesManager } from '@/lib/managers/instances';
import { ModLoader } from '@/types/instances';

defineProps<{
  icon?: string,
  name: string,
  mc_version: string,
  mod_loader: ModLoader,
  mod_loader_version: string
}>();
</script>

<template>
  <div class="min-w-[250px] flex items-center justify-between hover:bg-[#26546c]/50 hover:border-sky-500 bg-[#1b1d21] border-2 border-[#2c2f34] py-3 px-4 rounded-lg transition-colors duration-300 hover:cursor-pointer">

    <div class="flex items-center gap-4 whitespace-nowrap">
      <img :src="icon" class="shrink-0 object-cover size-16 rounded-md border-2 border-[#525261] bg-[#2a2a31]" alt="Instance Icon">

      <div class="leading-tight">
        <h1 class="text-white text-lg">{{ name }}</h1>
        <p class="text-gray-400 text-sm">Version: {{ mc_version }}</p>
        <p class="text-gray-400 text-sm">Mod Loader: {{ mod_loader }} {{ mod_loader_version }}</p>
      </div>
    </div>

    <button
    @click.stop="async () => await instancesManager.launch_instance(name)" 
    class="cursor-pointer flex items-center
 justify-center size-10 rounded-full bg-sky-500 hover:bg-sky-600 transition-colors shrink-0">
      <PlayIcon class="size-5 text-white" />
    </button>
  </div>
</template>
