// crates/sl-frontend/src/pages/StorePage.vue
<script setup lang="ts">
import { ref, computed, watch, onMounted } from 'vue';
import StoreCard from '../components/StoreCard.vue';
import StoreSearchBar from '../components/StoreSearchBar.vue';
import { StoreCategoryType, StoreSearch, StoreType } from '../types/store';
import { fetchStoreSearch } from '../lib/commands/store';
import StoreLoadingState from '../components/StoreLoadingState.vue';
import OptionSelector from '../components/OptionSelector.vue';

const storeType = ref<StoreType>('modrinth');
const storeCategory = ref<StoreCategoryType>("modpacks");

const searchQuery = ref("");
const storeItems = ref<StoreSearch>();

const storePage = ref(1);
const loading = ref(false);

const loadStoreItems = async () => {
  loading.value = true;
  try {
    const result = await fetchStoreSearch(searchQuery.value, storeType.value, storeCategory.value, storePage.value);
    storeItems.value = result;
  } catch (e) {
    console.error(e);
    storeItems.value = undefined;
  } finally {
    loading.value = false;
  }
};

onMounted(loadStoreItems);
watch([searchQuery, storeCategory, storeType], loadStoreItems)

const combinedItems = computed(() => {
  if (!storeItems.value) return [];

  if ('hits' in storeItems.value) {
    return storeItems.value.hits.map(item => ({
      id: item.id,
      title: item.title,
      slug: item.slug,
      description: item.description,
      downloads: item.downloads,
      author: item.author,
      icon: item.icon_url || 'https://cdn.modrinth.com/placeholder.svg'
    }));
  }
  if ('data' in storeItems.value) {
    return storeItems.value.data.map(item => ({
      id: item.id,
      title: item.name,
      slug: item.slug,
      description: item.summary,
      downloads: 0,
      author: item.authors[0].name,
      icon: item.logo?.url || 'https://cdn.modrinth.com/placeholder.svg'
    }));
  }
  return [];
});
</script>

<template>
  <main class="flex flex-col gap-3 p-6 pb-18 overflow-y-auto overflow-x-hidden">
    <div class="flex gap-2">
      <OptionSelector v-model:selectedValue="storeType" :values="['modrinth', 'curseforge']" />
      <OptionSelector v-model:selectedValue="storeCategory" :values="['modpacks', 'mods', 'shaderpacks', 'resourcepacks']" />
    </div>
    
    <StoreSearchBar v-model:searchQuery="searchQuery" :category="storeCategory" />

    <StoreLoadingState v-if="loading" :storeType="storeType" :category="storeCategory" />

    <div v-else class="flex flex-col gap-3">
      <StoreCard v-for="item in combinedItems" :key="item.id" :title="item.title" :description="item.description"
        :downloads="item.downloads" :author="item.author" :icon="item.icon" :slug="item.slug" />
    </div>
  </main>
</template>

// crates/sl-frontend/src/pages/store-page.tsx
import { useEffect, useState } from 'react';
import { StoreCard } from '@/components/store-card';
import { Input } from '@/components/ui/input';
import { SearchIcon, WifiOff, Loader2, AlertCircle } from 'lucide-react';
import { StoreCategorySelector } from '@/components/store-category-selector';
import { SearchResult } from '@/lib/types/store/modrinth';
import { getModrinthStoreSearchResult } from '@/lib/commands/store';

export const StorePage = () => {
	const [searchResult, setSearchResult] = useState<SearchResult>();
	const [searchQuery, setSearchQuery] = useState('');
	const [category, setCategory] = useState('modpack');
	const [loading, setLoading] = useState(false);
	const [error, setError] = useState<string | null>(null);
	const [isOnline, setIsOnline] = useState(true);

	useEffect(() => {
		const checkOnline = () => setIsOnline(navigator.onLine);
		window.addEventListener('online', checkOnline);
		window.addEventListener('offline', checkOnline);

		checkOnline();

		return () => {
			window.removeEventListener('online', checkOnline);
			window.removeEventListener('offline', checkOnline);
		};
	}, []);

	useEffect(() => {
		const fetch = async () => {
			if (!isOnline) {
				setError('offline');
				return;
			}

			setLoading(true);
			setError(null);

			try {
				let result = await getModrinthStoreSearchResult(searchQuery, category, 0);
				setSearchResult(result);
			} catch (err) {
				setError('failed');
			} finally {
				setLoading(false);
			}
		};

		fetch();
	}, [searchQuery, category, isOnline]);

	return (
		<div className="flex flex-col gap-3">
			<StoreCategorySelector
				values={['Modrinth', 'Curseforge']}
				defaultValue="modrinth"
			/>

			<StoreCategorySelector
				values={['Modpack', 'Mod', 'Shader', 'Resourcepack', 'Datapack']}
				defaultValue="modpack"
				onValueChange={(value: string) => setCategory(value.toLowerCase())}
			/>

			<Input
				icon={<SearchIcon className="w-4 h-4" />}
				placeholder="Search modpacks..."
				value={searchQuery}
				onChange={(e) => setSearchQuery(e.target.value)}
			/>

			{loading && (
				<div className="flex items-center justify-center gap-2 text-muted-foreground mt-4">
					<Loader2 className="animate-spin w-5 h-5" />
					<span>Loading...</span>
				</div>
			)}

			{error === 'offline' && (
				<div className="flex flex-col items-center justify-center h-[50vh] text-muted-foreground gap-3">
					<WifiOff className="w-16 h-16 text-gray-400" />
					<h2 className="text-xl font-semibold">You're offline</h2>
					<p className="text-sm">Please check your internet connection.</p>
				</div>
			)}

			{error === 'failed' && (
				<div className="flex items-center justify-center gap-2 text-red-500 mt-4">
					<AlertCircle className="w-5 h-5" />
					<span>Failed to load mods. Try again later.</span>
				</div>
			)}

			{!loading && !error && searchResult?.hits.length === 0 && (
				<div className="flex items-center justify-center text-muted-foreground mt-4">
					<span>No results found.</span>
				</div>
			)}

			{!loading &&
				!error &&
				searchResult?.hits.map((hit) => (
					<StoreCard
						author={hit.author}
						description={hit.description}
						downloads={hit.downloads}
						followers={hit.follows}
						imageUrl={hit.icon_url || ''}
						name={hit.title}
						slug={hit.slug}
						key={hit.slug}
					/>
				))}
		</div>
	);
};
