// crates/sl-frontend/src/components/instances/InstanceCard.vue
<script lang="ts" setup>
import { PlayIcon } from 'lucide-vue-next';
import { instancesManager } from '@/lib/managers/instances';
import { ModLoader } from '@/types/instances';

defineProps<{
  icon?: string,
  name: string,
  mc_version: string,
  mod_loader: ModLoader,
  mod_loader_version: string
}>();
</script>

<template>
  <div class="flex items-center justify-between hover:bg-[#26546c]/50 hover:border-sky-500 bg-[#1b1d21] border-2 border-[#2c2f34] py-3 px-4 rounded-lg transition-colors duration-300 hover:cursor-pointer">

    <div class="flex items-center gap-4 whitespace-nowrap min-w-0">
      <img :src="icon" class="shrink-0 object-cover size-16 rounded-md border-2 border-[#525261] bg-[#2a2a31]" alt="Instance Icon">

      <div class="leading-tight min-w-0">
        <h1 class="text-white text-lg whitespace-nowrap truncate">{{ name }}</h1>
        <p class="text-gray-400 text-sm whitespace-nowrap truncate">{{ mc_version }} {{ mod_loader }} {{ mod_loader_version }}</p>
      </div>
    </div>

    <button
    @click.stop="async () => await instancesManager.launch_instance(name)" 
    class="cursor-pointer flex items-center
 justify-center size-10 rounded-full bg-sky-500 hover:bg-sky-600 transition-colors shrink-0">
      <PlayIcon class="size-5 text-white" />
    </button>
  </div>
</template>

// crates/sl-frontend/src/components/layout/pages/instances/instance-card.tsx
import { Instance } from '@/lib/types/instances';
import { Blocks, Gamepad, Gem, Pickaxe, Sword } from 'lucide-react';
import { useNavigate } from 'react-router-dom';

export const InstanceCard = ({ game_metadata, mod_loader, name }: Instance) => {
	const getIconByTitle = (title: string) => {
		const lowerTitle = title.toLowerCase();
		if (lowerTitle.includes('survival'))
			return <Pickaxe className="w-8 h-8 text-emerald-400" />;
		if (lowerTitle.includes('pvp') || lowerTitle.includes('combat'))
			return <Sword className="w-8 h-8 text-rose-400" />;
		if (lowerTitle.includes('creative'))
			return <Gem className="w-8 h-8 text-violet-400" />;
		return <Blocks className="w-8 h-8 text-blue-400" />;
	};

	const navigate = useNavigate();

	return (
		<div
			className="rounded-xl bg-[#1D1F2B] p-5 flex gap-4 items-center group cursor-pointer transition-colors hover:shadow-lg hover:bg-[#232631]/90"
			onClick={() => {
				navigate(`/instances/${name}`, { state: name });
			}}
		>
			<div className="w-12 h-12 rounded-xl bg-[#2A2F3F] group-hover:bg-[#33394D] flex items-center justify-center transition-colors shadow-inner">
				{getIconByTitle(name)}
			</div>

			<div className="flex flex-col justify-center gap-1 overflow-hidden">
				<h3 className="text-white text-lg font-semibold leading-tight truncate group-hover:text-sky-400 transition-colors">
					{name}
				</h3>
				<div className="flex items-center text-gray-400 text-sm gap-1 truncate">
					<Gamepad className="w-4 h-4" />
					<span className="truncate">
						{mod_loader} &middot; {game_metadata.id}
					</span>
				</div>
			</div>
		</div>
	);
};
